name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Start Kubernetes minikube
        uses: medyagh/setup-minikube@master
      - name: Try the Kubernetes cluster
        run: kubectl get nodes
      - name: Build and test
        working-directory: rentalService
        run: |
          export SHELL=/bin/bash
          ./gradlew build
          docker build -f ./Dockerfile -t local/rental .
          docker images
          

      - name: Deploy app on Kubernetes
        run: |
          kubectl apply -f rental-deployment.yml
          kubectl apply -f rental-service.yml
          kubectl get pods
          kubectl get services
          kubectl get deployments