name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Start Kubernetes minikube
        uses: medyagh/setup-minikube@master # external action (be careful to check what external actions do before using them)
      - name: Try the Kubernetes cluster
        run: kubectl get nodes
      - name: Build and test
        working-directory: rentalService
        run: |
          export SHELL=/bin/bash
          ./gradlew build
          eval $(minikube docker-env) # this avoid pulling the image from the repository
          docker build -f ./Dockerfile -t rentalservice .
          docker images
          cd ..
      - name: Deploy the image to minikube
        run: |
          kubectl apply -f global-deployment.yml
      - name: Get Kubernetes service URL
        run: |
          kubectl get pods
          kubectl wait --for=condition=ready pod -l app=rentalservice --timeout=60s pod -l app=rentalservice
          kubectl get pods
          minikube service list
          minikube service rentalservice --url
          echo "------------------opening the service------------------"
      - name: Test Kubernetes service URL
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 10
          max_attempts: 4
          command: curl $(minikube service rentalservice --url)/cars
      - name: Log Kubernetes minikube
        run: |
          kubectl logs $(kubectl get pods -l app=rentalservice -o name)