name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Build and test
        run: |
          export SHELL=/bin/bash
          ./gradlew build
          docker build -f ./Dockerfile -t local/rental .
          docker images